apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wdjp18xih-python 
  janus-idp.io/tekton: wdjp18xih-python
  backstage.io/kubernetes-id: wdjp18xih-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wdjp18xih-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  