apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wdjp18xih-python-gitops
  description: This is GitOps manifest for wdjp18xih-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: wdjp18xih-python
    janus-idp.io/tekton: wdjp18xih-python 
    backstage.io/kubernetes-id: wdjp18xih-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wdjp18xih-python
