apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wdjp18xih-python
  janus-idp.io/tekton: wdjp18xih-python
  backstage.io/kubernetes-id: wdjp18xih-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wdjp18xih-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
