apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: wdjp18xih-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wdjp18xih-python 
  name: wdjp18xih-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: wdjp18xih-python
    weight: 100 
